- app/models/athelete_sport.rb
- app/models/booking.rb
- app/models/coached_sport.rb
- app/models/session.rb
- app/models/user.rb
- db/migrate/20190225155833_create_users.rb
- db/migrate/20190225160908_create_sessions.rb
- db/migrate/20190225161014_create_bookings.rb
- db/migrate/20190225162520_create_athelete_sports.rb
- db/migrate/20190225162638_create_coached_sports.rb
- db/schema.rb
- test/models/athelete_sport_test.rb
- test/models/booking_test.rb
- test/models/coached_sport_test.rb
- test/models/session_test.rb
- test/models/user_test.rb
Hey Guys. Please can you check the first models I crated. I have not yet added reviews as it is slightly more complex.
> added all models except reviews

- db/schema.rb
Sorry guys now i have migrated the db.
> schema updated

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20190225181946_remove_email_from_users.rb
- db/migrate/20190225183142_add_email_to_users.rb
- db/migrate/20190225183524_add_devise_to_users.rb
- db/schema.rb
- test/models/user_test.rb
Devices has now been added so if you go to http://localhost:3000/users/sign_up there is a sign up sheet. However dont add anything yet we need to add more fields such as whether they are  coach or an athlete
> devises has been added so now have a sign up form

- app/models/user.rb
Added validations to the user model
> added validations to user model

- db/migrate/20190226114813_add_user_image_to_users.rb
- db/schema.rb
added user image to user table
> added user-image column to use table

- app/models/user_sport.rb
- db/migrate/20190226150740_create_sessions_table.rb
- db/migrate/20190226150850_create_bookings.rb
- db/migrate/20190226151502_remove_spportnamefrom_sessions.rb
- db/migrate/20190226151558_add_coach_id_to_sessions.rb
- db/migrate/20190226151710_remove_user_id_from_sessions.rb
- db/migrate/20190226152119_rename_sports_id_in_sessions.rb
Sorry Guys - forgot to save the migrations on the last push. Try to pull again and db:migrate 👍
> saved migrations

- app/controllers/sports_controller.rb
- config/routes.rb
- db/seeds.rb
- test/controllers/sports_controller_test.rb
I have added the sports controller and added some sports seeds for testing purposes
> added sports controller and seeded some sports

- app/views/devise/registrations/new.html.erb
please check sign up form advise if any additional items
> added fields to signup form

- app/views/pages/home.html.erb
> linking the buttons of form to sign up

- app/controllers/sports_controller.rb
- app/controllers/user_sports_controller.rb
- app/models/user_sport.rb
- test/controllers/user_sports_controller_test.rb
I have taken the sports controller out the reason for this is that sports will be a set list which is not dynamic. The same way that we had ingredients in our cocktails exersize. We can simply have a drop down list of sports to build a users user-sports list (IE the list of their sports)
> removed sports controller and added user-sports-controller

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_flashes.html.erb
- db/seeds.rb
- test/controllers/users_controller_test.rb
1. A coach checkbox to sign up form
2. Changed location to address in seed file, user model and user controller
3. Commented set_user from users controller as devises does this for us
4. Log out function now works
5. On home page if statement which shows sign in sign up buttons if not signed in or log out if signed in
> Completed the devices functionality for sign-in, sign-up and log out

- app/controllers/bookings_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/sessions/index.html.erb
- app/views/users/_athlete_profile.html.erb
- app/views/users/_coach_profile.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
> Booking controller

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/uploaders/user_image_uploader.rb
- app/views/devise/registrations/new.html.erb
- app/views/pages/home.html.erb
- added carrier wave gem (please bundle install)
- added the image uploader to the form
- linked the avatar on the home page to current_user.user_image 
-added a validation to user that user_image is compulsary
> added image uploader and linked to current user

- app/views/sessions/index.html.erb
As seen working together on this
> linking coach prfile to reuslts page

- app/views/sessions/index.html.erb
- app/views/users/_athlete_profile.html.erb
getting ready for demo tidied up CSS of profiles
> tidy up css for demo

- Gemfile
- Gemfile.lock
added the missing gemfile for geocoder run bundle when pulling
> added the gemfile missing for geocoder

- app/views/users/_coach_profile.html.erb
Hey guys just tidied up the HTML for the coach dash board with Esther. CSS needs to be corrected as the "Add a sport" button is hiding behind some divs. Esther is adding this to the Trello board
> tidied up html on coach dash board. css needs to be fixed

- app/views/sessions/index.html.erb
- app/views/users/index.html.erb
move map as it was showing on sessions page rather than coaches index.
> moved map as in wrong place, now in correct place though not working

- app/controllers/sessions_controller.rb
> updated controller

- app/javascript/plugins/init_mapbox.js
- app/views/users/index.html.erb
> tags on map now working

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
- app/views/users/_athlete_profile.html.erb
- app/views/users/_coach_profile.html.erb
Bookings can now be deleted and are displayed on the user's profiles. CSS needs to be fixed
> added the current user's bookings to both the athlete and coach profiles

- app/javascript/components/banner.js
- app/javascript/packs/application.js
- app/views/pages/home.html.erb
- package.json
- yarn.lock
Added type writer to home page to add some cool style 😎
> typewritter added to homepage

- app/controllers/users_controller.rb
added near me functionality working to 2 km
> near me fuctionality included in map search

- app/assets/stylesheets/components/_card.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> fixed card image size, added shadow to card, styling sign in form

- app/controllers/registrations_controller.rb
- app/models/session.rb
- config/routes.rb
Sign Up Form will now redirect coaches to their dashboard and athletes to their home
> redirects coaches to their dashboard on sign up:

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/sessions/index.html.erb
- app/views/users/_coach_profile.html.erb
> styling for ranking and captialize the sign up and sign in

- app/views/pages/home.html.erb
changed tag line on home page cards
> altered tag lines

- app/javascript/plugins/init_mapbox.js
ensure time of the popup to click on details
> marker hover timeout
